export const birdSpecies = [
    { label: "Wilson's Storm-petrel(Oceanites oceanicus)", value: "Wilson's Storm-petrel(Oceanites oceanicus)" },
     { label: "White-faced Storm-petrel(Pelagodroma marina)", value: "White-faced Storm-petrel(Pelagodroma marina)" }, 
    { label: "Black-bellied Storm-petrel(Fregetta tropica)", value: "Black-bellied Storm-petrel(Fregetta tropica)" }, 
    { label: "Swinhoe's Storm-petrel(Hybrobates monorhis)", value: "Swinhoe's Storm-petrel(Hybrobates monorhis)" }, 
    { label: "Cape Petrel(Daption capense)", value: "Cape Petrel(Daption capense)" },
     { label: "Barau's Petrel(Pterodroma baraui)", value: "Barau's Petrel(Pterodroma baraui)" },
     { label: "Wedge-tailed Shearwater(Ardenna pacifica)", value: "Wedge-tailed Shearwater(Ardenna pacifica)" },
     { label: "Short-tailed Shearwater(Ardenna tenuirostris)", value: "Short-tailed Shearwater(Ardenna tenuirostris)" }, 
    { label: "Sooty Shearwater(Ardenna grisea)", value: "Sooty Shearwater(Ardenna grisea)" },
     { label: "Flesh-footed Shearwater(Ardenna carneipes)", value: "Flesh-footed Shearwater(Ardenna carneipes)" }, 
    { label: "Streaked Shearwater(Calonectris leucomelas)", value: "Streaked Shearwater(Calonectris leucomelas)" },
     { label: "Bulwer's Petrel(Bulweria bulwerii)", value: "Bulwer's Petrel(Bulweria bulwerii)" },
     { label: "Jouanin's Petrel(Bulweria fallax)", value: "Jouanin's Petrel(Bulweria fallax)" }, 
    { label: "Lesser Adjutant(Leptoptilos javanicus)", value: "Lesser Adjutant(Leptoptilos javanicus)" }, 
    { label: "Painted Stork(Mycteria leucocephala)", value: "Painted Stork(Mycteria leucocephala)" },
     { label: "Asian Openbill(Anastomus oscitans)", value: "Asian Openbill(Anastomus oscitans)" }, 
    { label: "Black Stork(Ciconia nigra)", value: "Black Stork(Ciconia nigra)" },
     { label: "Asian Woollyneck(Ciconia episcopus)", value: "Asian Woollyneck(Ciconia episcopus)" },
     { label: "White Stork(Ciconia ciconia)", value: "White Stork(Ciconia ciconia)" },
     { label: "Black-necked Stork(Ephippiorhynchus asiaticus)", value: "Black-necked Stork(Ephippiorhynchus asiaticus)" },
     { label: "Eurasian Spoonbill(Platalea leucorodia)", value: "Eurasian Spoonbill(Platalea leucorodia)" },
     { label: "Black-headed Ibis(Threskiornis melanocephalus)", value: "Black-headed Ibis(Threskiornis melanocephalus)" },
     { label: "Glossy Ibis(Plegadis falcinellus)", value: "Glossy Ibis(Plegadis falcinellus)" },
     { label: "Eurasian Bittern(Botaurus stellaris)", value: "Eurasian Bittern(Botaurus stellaris)" },
     { label: "Yellow Bittern(Ixobrychus sinensis)", value: "Yellow Bittern(Ixobrychus sinensis)" },
     { label: "Schrenck’s Bittern(Ixobrychus eurhythmus)", value: "Schrenck’s Bittern(Ixobrychus eurhythmus)" },
     { label: "Cinnamon Bittern(Ixobrychus cinnamomeus)", value: "Cinnamon Bittern(Ixobrychus cinnamomeus)" },
     { label: "Black Bittern(Ixobrychus flavicollis)", value: "Black Bittern(Ixobrychus flavicollis)" },
     { label: "Malay Night-heron(Gorsachius melanolophus)", value: "Malay Night-heron(Gorsachius melanolophus)" },
     { label: "Black-crowned Night-heron(Nycticorax nycticorax)", value: "Black-crowned Night-heron(Nycticorax nycticorax)" },
     { label: "Green-backed Heron(Butorides striata)", value: "Green-backed Heron(Butorides striata)" },
     { label: "Indian Pond-heron(Ardeola grayii)", value: "Indian Pond-heron(Ardeola grayii)" },
     { label: "Chinese Pond-heron(Ardeola bacchus)", value: "Chinese Pond-heron(Ardeola bacchus)" },
     { label: "Cattle Egret(Bubulcus ibis)", value: "Cattle Egret(Bubulcus ibis)" },
     { label: "Grey Heron(Ardea cinerea)", value: "Grey Heron(Ardea cinerea)" },
     { label: "Goliath Heron(Ardea goliath)", value: "Goliath Heron(Ardea goliath)" },
     { label: "Purple Heron(Ardea purpurea)", value: "Purple Heron(Ardea purpurea)" },
     { label: "Great White Egret(Ardea alba)", value: "Great White Egret(Ardea alba)" },
     { label: "Intermediate Egret(Ardea intermedia)", value: "Intermediate Egret(Ardea intermedia)" },
     { label: "Little Egret(Egretta garzetta)", value: "Little Egret(Egretta garzetta)" },
     { label: "Western Reef-egret(Egretta gularis)", value: "Western Reef-egret(Egretta gularis)" },
     { label: "Spot-billed Pelican(Pelecanus philippensis)", value: "Spot-billed Pelican(Pelecanus philippensis)" },
     { label: "Lesser Frigatebird (Fregata ariel)", value: "Lesser Frigatebird (Fregata ariel)" },
     { label: "Great Frigatebird (Fregata minor)", value: "Great Frigatebird (Fregata minor)" },
     { label: "Christmas Frigatebird (Fregata andrewsi)", value: "Christmas Frigatebird (Fregata andrewsi)" },
     { label: "Red-footed Booby (Sula sula)", value: "Red-footed Booby (Sula sula)" },
     { label: "Brown Booby (Sula leucogaster)", value: "Brown Booby (Sula leucogaster)" },
     { label: "Masked Booby (Sula dactylatra)", value: "Masked Booby (Sula dactylatra)" },
     { label: "Little Cormorant (Microcarbo niger)", value: "Little Cormorant (Microcarbo niger)" },
     { label: "Great Cormorant (Phalacrocorax carbo)", value: "Great Cormorant (Phalacrocorax carbo)" },
     { label: "Indian Cormorant (Phalacrocorax fuscicollis)", value: "Indian Cormorant (Phalacrocorax fuscicollis)" },
     { label: "Oriental Darter (Anhinga melanogaster)", value: "Oriental Darter (Anhinga melanogaster)" },
     { label: "Indian Thick-knee (Burhinus indicus)", value: "Indian Thick-knee (Burhinus indicus)" },
     { label: "Great Thick-knee (Esacus recurvirostris)", value: "Great Thick-knee (Esacus recurvirostris)" },
     { label: "Eurasian Oystercatcher (Haematopus ostralegus)", value: "Eurasian Oystercatcher (Haematopus ostralegus)" },
     { label: "Pied Avocet (Recurvirostra avosetta)", value: "Pied Avocet (Recurvirostra avosetta)" },
     { label: "Black-winged Stilt (Himantopus himantopus)", value: "Black-winged Stilt (Himantopus himantopus)" },
     { label: "Grey Plover (Pluvialis squatarola)", value: "Grey Plover (Pluvialis squatarola)" },
     { label: "Pacific Golden Plover (Pluvialis fulva)", value: "Pacific Golden Plover (Pluvialis fulva)" },
     { label: "Common Ringed Plover (Charadrius hiaticula)", value: "Common Ringed Plover (Charadrius hiaticula)" },
     { label: "Little Ringed Plover (Charadrius dubius)", value: "Little Ringed Plover (Charadrius dubius)" },
     { label: "Kentish Plover (Charadrius alexandrinus)", value: "Kentish Plover (Charadrius alexandrinus)" },
     { label: "Lesser Sandplover (Charadrius mongolus)", value: "Lesser Sandplover (Charadrius mongolus)" },
     { label: "Greater Sandplover (Charadrius leschenaultii)", value: "Greater Sandplover (Charadrius leschenaultii)" },
     { label: "Caspian Plover (Charadrius asiaticus)", value: "Caspian Plover (Charadrius asiaticus)" },
     { label: "Oriental Plover (Charadrius veredus)", value: "Oriental Plover (Charadrius veredus)" },
     { label: "Yellow-wattled Lapwing (Vanellus malabaricus)", value: "Yellow-wattled Lapwing (Vanellus malabaricus)" },
     { label: "Grey-headed Lapwing (Vanellus cinereus)", value: "Grey-headed Lapwing (Vanellus cinereus)" },
     { label: "Red-wattled Lapwing (Vanellus indicus)", value: "Red-wattled Lapwing (Vanellus indicus)" },
     { label: "Sociable Lapwing (Vanellus gregarius)", value: "Sociable Lapwing (Vanellus gregarius)" },
     { label: "Greater Painted-snipe (Rostratula benghalensis)", value: "Greater Painted-snipe (Rostratula benghalensis)" },
     { label: "Pheasant-tailed Jacana (Hydrophasianus chirurgus)", value: "Pheasant-tailed Jacana (Hydrophasianus chirurgus)" },
     { label: "Whimbrel (Numenius phaeopus)", value: "Whimbrel (Numenius phaeopus)" },
     { label: "Eurasian Curlew (Numenius arquata)", value: "Eurasian Curlew (Numenius arquata)" },
     { label: "Bar-tailed Godwit (Limosa lapponica)", value: "Bar-tailed Godwit (Limosa lapponica)" },
     { label: "Black-tailed Godwit (Limosa limosa)", value: "Black-tailed Godwit (Limosa limosa)" },
     { label: "Ruddy Turnstone (Arenaria interpres)", value: "Ruddy Turnstone (Arenaria interpres)" },
     { label: "Great Knot (Calidris tenuirostris)", value: "Great Knot (Calidris tenuirostris)" },
     { label: "Red Knot (Calidris canutus)", value: "Red Knot (Calidris canutus)" },
     { label: "Ruff (Calidris pugnax)", value: "Ruff (Calidris pugnax)" },
     { label: "Broad-billed Sandpiper (Calidris falcinellus)", value: "Broad-billed Sandpiper (Calidris falcinellus)" },
     { label: "Sharp-tailed Sandpiper (Calidris acuminata)", value: "Sharp-tailed Sandpiper (Calidris acuminata)" },
     { label: "Curlew Sandpiper (Calidris ferruginea)", value: "Curlew Sandpiper (Calidris ferruginea)" },
     { label: "Temminck's Stint (Calidris temminckii)", value: "Temminck's Stint (Calidris temminckii)" },
     { label: "Long-toed Stint (Calidris subminuta)", value: "Long-toed Stint (Calidris subminuta)" },
     { label: "Spoon-billed Sandpiper (Calidris pygmaea)", value: "Spoon-billed Sandpiper (Calidris pygmaea)" },
     { label: "Red-necked Stint (Calidris ruficollis)", value: "Red-necked Stint (Calidris ruficollis)" },
     { label: "Sanderling (Calidris alba)", value: "Sanderling (Calidris alba)" },
     { label: "Dunlin (Calidris alpina)", value: "Dunlin (Calidris alpina)" },
     { label: "Little Stint (Calidris minuta)", value: "Little Stint" },
{ label: "Buff-breasted Sandpiper (Calidris subruficollis)", value: "Buff-breasted Sandpiper" },
{ label: "Pectoral Sandpiper (Calidris melanotos)", value: "Pectoral Sandpiper" },
{ label: "Asian Dowitcher (Limnodromus semipalmatus)", value: "Asian Dowitcher" },
{ label: "Eurasian Woodcock (Scolopax rusticola)", value: "Eurasian Woodcock" },
{ label: "Sri Lanka Spurfowl (Galloperdix bicalcarata)", value: "Sri Lanka Spurfowl (Galloperdix bicalcarata)" },
{ label: "Indian Peafowl (Pavo cristatus)", value: "Indian Peafowl (Pavo cristatus)" },
{ label: "Rain Quail (Coturnix coromandelica)", value: "Rain Quail (Coturnix coromandelica)" },
{ label: "Asian Blue Quail (Synoicus chinensis)", value: "Asian Blue Quail (Synoicus chinensis)" },
{ label: "Jungle Bush-quail (Perdicula asiatica)", value: "Jungle Bush-quail (Perdicula asiatica)" },
{ label: "Painted Francolin (Francolinus pictus)", value: "Painted Francolin (Francolinus pictus)" },
{ label: "Grey Francolin (Francolinus pondicerianus)", value: "Grey Francolin (Francolinus pondicerianus)" },
{ label: "Sri Lanka Junglefowl (Gallus lafayettii)", value: "Sri Lanka Junglefowl (Gallus lafayettii)" },
{ label: "Fulvous Whistling-duck (Dendrocygna bicolor)", value: "Fulvous Whistling-duck (Dendrocygna bicolor)" },
{ label: "Lesser Whistling-duck (Dendrocygna javanica)", value: "Lesser Whistling-duck (Dendrocygna javanica)" },
{ label: "Bar-headed Goose (Anser indicus)", value: "Bar-headed Goose (Anser indicus)" },
{ label: "Greylag Goose (Anser anser)", value: "Greylag Goose (Anser anser)" },
{ label: "Ruddy Shelduck (Tadorna ferruginea)", value: "Ruddy Shelduck (Tadorna ferruginea)" },
{ label: "African Comb Duck (Sarkidiornis melanotos)", value: "African Comb Duck (Sarkidiornis melanotos)" },
{ label: "Cotton Pygmy-goose (Nettapus coromandelianus)", value: "Cotton Pygmy-goose (Nettapus coromandelianus)" },
{ label: "Tufted Duck (Aythya fuligula)", value: "Tufted Duck (Aythya fuligula)" },
{ label: "Garganey (Spatula querquedula)", value: "Garganey (Spatula querquedula)" },
{ label: "Northern Shoveler (Spatula clypeata)", value: "Northern Shoveler (Spatula clypeata)" },
{ label: "Gadwall (Mareca strepera)", value: "Gadwall (Mareca strepera)" },
{ label: "Eurasian Wigeon (Mareca penelope)", value: "Eurasian Wigeon (Mareca penelope)" },
{ label: "Indian Spot-billed Duck (Anas poecilorhyncha)", value: "Indian Spot-billed Duck (Anas poecilorhyncha)" },
{ label: "Northern Pintail (Anas acuta)", value: "Northern Pintail (Anas acuta)" },
{ label: "Common Teal (Anas crecca)", value: "Common Teal (Anas crecca)" },
{ label: "Little Grebe (Tachybaptus ruficollis)", value: "Little Grebe (Tachybaptus ruficollis)" },
{ label: "Greater Flamingo (Phoenicopterus roseus)", value: "Greater Flamingo (Phoenicopterus roseus)" },
{ label: "Red-billed Tropicbird (Phaethon aethereus)", value: "Red-billed Tropicbird (Phaethon aethereus)" },
{ label: "White-tailed Tropicbird (Phaethon lepturus)", value: "White-tailed Tropicbird (Phaethon lepturus)" },
{ label: "Rock Dove (Columba livia)", value: "Rock Dove (Columba livia)" },
{ label: "Sri Lanka Woodpigeon (Columba torringtoniae)", value: "Sri Lanka Woodpigeon (Columba torringtoniae)" },
{ label: "Pale-capped Pigeon (Columba punicea)", value: "Pale-capped Pigeon (Columba punicea)" },
{ label: "Oriental Turtle-dove (Streptopelia orientalis)", value: "Oriental Turtle-dove (Streptopelia orientalis)" },
{ label: "Eurasian Collared-dove (Streptopelia decaocto)", value: "Eurasian Collared-dove (Streptopelia decaocto)" },
{ label: "Red Turtle-dove (Streptopelia tranquebarica)", value: "Red Turtle-dove (Streptopelia tranquebarica)" },
{ label: "Western Spotted Dove (Spilopelia suratensis)", value: "Western Spotted Dove (Spilopelia suratensis)" },
{ label: "Grey-capped Emerald Dove (Chalcophaps indica)", value: "Grey-capped Emerald Dove (Chalcophaps indica)" },
{ label: "Orange-breasted Green-pigeon (Treron bicinctus)", value: "Orange-breasted Green-pigeon (Treron bicinctus)" },
{ label: "Sri Lanka Green-pigeon (Treron pompadora)", value: "Sri Lanka Green-pigeon (Treron pompadora)" },
{ label: "Yellow-footed Green-pigeon (Treron phoenicopterus)", value: "Yellow-footed Green-pigeon (Treron phoenicopterus)" },
{ label: "Green Imperial-pigeon (Ducula aenea)", value: "Green Imperial-pigeon (Ducula aenea)" },
{ label: "Sri Lanka Frogmouth (Batrachostomus moniliger)", value: "Sri Lanka Frogmouth (Batrachostomus moniliger)" },
{ label: "Great Eared-nightjar (Lyncornis macrotis)", value: "Great Eared-nightjar (Lyncornis macrotis)" },
{ label: "Jungle Nightjar (Caprimulgus indicus)", value: "Jungle Nightjar (Caprimulgus indicus)" },
{ label: "Jerdon’s Nightjar (Caprimulgus atripennis)", value: "Jerdon’s Nightjar (Caprimulgus atripennis)" },
{ label: "Indian Nightjar (Caprimulgus asiaticus)", value: "Indian Nightjar (Caprimulgus asiaticus)" },
{ label: "Crested Treeswift (Hemiprocne coronata)", value: "Crested Treeswift (Hemiprocne coronata)" },
{ label: "Brown-backed Needletail (Hirundapus giganteus)", value: "Brown-backed Needletail (Hirundapus giganteus)" },
{ label: "Indian Swiftlet (Aerodramus unicolor)", value: "Indian Swiftlet (Aerodramus unicolor)" },
{ label: "Asian Palm-swift (Cypsiurus balasiensis)", value: "Asian Palm-swift (Cypsiurus balasiensis)" },
{ label: "Alpine Swift (Tachymarptis melba)", value: "Alpine Swift (Tachymarptis melba)" },
{ label: "Pacific Swift (Apus pacificus)", value: "Pacific Swift (Apus pacificus)" },
{ label: "Little Swift (Apus affinis)", value: "Little Swift (Apus affinis)" },
{ label: "Green-billed Coucal (Centropus chlororhynchos)", value: "Green-billed Coucal (Centropus chlororhynchos)" },
{ label: "Greater Coucal (Centropus sinensis)", value: "Greater Coucal (Centropus sinensis)" },
{ label: "Sirkeer Malkoha (Taccocua leschenaultii)", value: "Sirkeer Malkoha (Taccocua leschenaultii)" },
{ label: "Red-faced Malkoha (Phaenicophaeus pyrrhocephalus)", value: "Red-faced Malkoha (Phaenicophaeus pyrrhocephalus)" },
{ label: "Blue-faced Malkoha (Phaenicophaeus viridirostris)", value: "Blue-faced Malkoha (Phaenicophaeus viridirostris)" },
{ label: "Jacobin Cuckoo (Clamator jacobinus)", value: "Jacobin Cuckoo (Clamator jacobinus)" },
{ label: "Chestnut-winged Cuckoo (Clamator coromandus)", value: "Chestnut-winged Cuckoo (Clamator coromandus)" },
{ label: "Western Koel (Eudynamys scolopaceus)", value: "Western Koel (Eudynamys scolopaceus)" },
{ label: "Asian Emerald Cuckoo (Chrysococcyx maculatus)", value: "Asian Emerald Cuckoo (Chrysococcyx maculatus)" },
{ label: "Banded Bay Cuckoo (Cacomantis sonneratii)", value: "Banded Bay Cuckoo (Cacomantis sonneratii)" },
{ label: "Grey-bellied Cuckoo (Cacomantis passerinus)", value: "Grey-bellied Cuckoo (Cacomantis passerinus)" },
{ label: "Fork-tailed Drongo-cuckoo (Surniculus dicruroides)", value: "Fork-tailed Drongo-cuckoo (Surniculus dicruroides)" },
{ label: "Common Hawk-cuckoo (Hierococcyx varius)", value: "Common Hawk-cuckoo (Hierococcyx varius)" },
{ label: "Indian Cuckoo (Cuculus micropterus)", value: "Indian Cuckoo (Cuculus micropterus)" },
{ label: "Common Cuckoo (Cuculus canorus)", value: "Common Cuckoo (Cuculus canorus)" },
{ label: "Lesser Cuckoo (Cuculus poliocephalus)", value: "Lesser Cuckoo (Cuculus poliocephalus)" },
{ label: "Slaty-legged Crake (Rallina eurizonoides)", value: "Slaty-legged Crake (Rallina eurizonoides)" },
{ label: "Eastern Water Rail (Rallus indicus)", value: "Eastern Water Rail (Rallus indicus)" },
{ label: "Slaty-breasted Rail (Lewinia striata)", value: "Slaty-breasted Rail (Lewinia striata)" },
{ label: "Corncrake (Crex crex)", value: "Corncrake (Crex crex)" },
{ label: "Ruddy-breasted Crake (Zapornia fusca)", value: "Ruddy-breasted Crake (Zapornia fusca)" },
{ label: "Baillon's Crake (Zapornia pusilla)", value: "Baillon's Crake (Zapornia pusilla)" },
{ label: "White-breasted Waterhen (Amaurornis phoenicurus)", value: "White-breasted Waterhen (Amaurornis phoenicurus)" },
{ label: "Watercock (Gallicrex cinerea)", value: "Watercock (Gallicrex cinerea)" },
{ label: "Purple Swamphen (Porphyrio porphyria)", value: "Purple Swamphen (Porphyrio porphyria)" },
{ label: "Common Moorhen (Gallinula chloropus)", value: "Common Moorhen (Gallinula chloropus)" },
{ label: "Common Coot (Fulica atra)", value: "Common Coot (Fulica atra)" },
{ label: "Sri Lanka Bay-owl (Phodilus assimilis)", value: "Sri Lanka Bay-owl (Phodilus assimilis)" },
{ label: "Common Barn-owl (Tyto alba)", value: "Common Barn-owl (Tyto alba)" },
{ label: "Brown Boobook (Ninox scutulata)", value: "Brown Boobook (Ninox scutulata)" },
{ label: "Jungle Owlet (Glaucidium radiatum)", value: "Jungle Owlet (Glaucidium radiatum)" },
{ label: "Chestnut-backed Owlet (Glaucidium castanotum)", value: "Chestnut-backed Owlet (Glaucidium castanotum)" },
{ label: "Serendib Scops-owl (Otus thilohoffmanni)", value: "Serendib Scops-owl (Otus thilohoffmanni)" },
{ label: "Indian Scops-owl (Otus bakkamoena)", value: "Indian Scops-owl (Otus bakkamoena)" },
{ label: "Oriental Scops-owl (Otus sunia)", value: "Oriental Scops-owl (Otus sunia)" },
{ label: "Short-eared Owl (Asio flammeus)", value: "Short-eared Owl (Asio flammeus)" },
{ label: "Brown Wood-owl (Strix leptogrammica)", value: "Brown Wood-owl (Strix leptogrammica)" },
{ label: "Spot-bellied Eagle-owl (Bubo nipalensis)", value: "Spot-bellied Eagle-owl (Bubo nipalensis)" },
{ label: "Brown Fish-owl (Ketupa zeylonensis)", value: "Brown Fish-owl (Ketupa zeylonensis)" },
{ label: "Osprey (Pandion haliaetus)", value: "Osprey (Pandion haliaetus)" },
{ label: "Black-winged Kite (Elanus caeruleus)", value: "Black-winged Kite (Elanus caeruleus)" },
{ label: "European Honey-buzzard (Pernis apivorus)", value: "European Honey-buzzard (Pernis apivorus)" },
{ label: "Oriental Honey-buzzard (Pernis ptilorhynchus)", value: "Oriental Honey-buzzard (Pernis ptilorhynchus)" },
{ label: "Jerdon’s Baza (Aviceda jerdoni)", value: "Jerdon’s Baza (Aviceda jerdoni)" },
{ label: "Black Baza (Aviceda leuphotes)", value: "Black Baza (Aviceda leuphotes)" },
{ label: "Egyptian Vulture (Neophron percnopterus)", value: "Egyptian Vulture (Neophron percnopterus)" },
{ label: "Crested Serpent-eagle (Spilornis cheela)", value: "Crested Serpent-eagle (Spilornis cheela)" },
{ label: "Mountain Hawk-eagle (Nisaetus nipalensis)", value: "Mountain Hawk-eagle (Nisaetus nipalensis)" },
{ label: "Changeable Hawk-eagle (Nisaetus cirrhatus)", value: "Changeable Hawk-eagle (Nisaetus cirrhatus)" },
{ label: "Rufous-bellied Eagle (Lophotriorchis kienerii)", value: "Rufous-bellied Eagle (Lophotriorchis kienerii)" },
{ label: "Black Eagle (Ictinaetus malaiensis)", value: "Black Eagle (Ictinaetus malaiensis)" },
{ label: "Greater Spotted Eagle (Clanga clanga)", value: "Greater Spotted Eagle (Clanga clanga)" },
{ label: "Bonelli's Eagle (Aquila fasciata)", value: "Bonelli's Eagle (Aquila fasciata)" },
{ label: "Booted Eagle (Hieraaetus pennatus)", value: "Booted Eagle (Hieraaetus pennatus)" },
{ label: "Western Marsh-harrier (Circus aeruginosus)", value: "Western Marsh-harrier (Circus aeruginosus)" },
{ label: "Pallid Harrier (Circus macrourus)", value: "Pallid Harrier (Circus macrourus)" },
{ label: "Pied Harrier (Circus melanoleucos)", value: "Pied Harrier (Circus melanoleucos)" },
{ label: "Montagu's Harrier (Circus pygargus)", value: "Montagu's Harrier (Circus pygargus)" },
{ label: "Crested Goshawk (Accipiter trivirgatus)", value: "Crested Goshawk (Accipiter trivirgatus)" },
{ label: "Shikra (Accipiter badius)", value: "Shikra (Accipiter badius)" },
{ label: "Besra (Accipiter virgatus)", value: "Besra (Accipiter virgatus)" },
{ label: "Eurasian Sparrowhawk (Accipiter nisus)", value: "Eurasian Sparrowhawk (Accipiter nisus)" },
{ label: "White-bellied Sea-eagle (Haliaeetus leucogaster)", value: "White-bellied Sea-eagle (Haliaeetus leucogaster)" },
{ label: "Grey-headed Fish-eagle (Haliaeetus ichthyaetus)", value: "Grey-headed Fish-eagle (Haliaeetus ichthyaetus)" },
{ label: "Brahminy Kite (Haliastur indus)", value: "Brahminy Kite (Haliastur indus)" },
{ label: "Black Kite (Milvus migrans)", value: "Black Kite (Milvus migrans)" },
{ label: "Himalayan Buzzard (Buteo burmanicus)", value: "Himalayan Buzzard (Buteo burmanicus)" },
{ label: "Long-legged Buzzard (Buteo rufinus)", value: "Long-legged Buzzard (Buteo rufinus)" },
{ label: "Malabar Trogon (Harpactes fasciatus)", value: "Malabar Trogon (Harpactes fasciatus)" },
{ label: "Sri Lanka Grey Hornbill (Ocyceros gingalensis)", value: "Sri Lanka Grey Hornbill (Ocyceros gingalensis)" },
{ label: "Malabar Pied Hornbill (Anthracoceros coronatus)", value: "Malabar Pied Hornbill (Anthracoceros coronatus)" },
{ label: "Common Hoopoe (Upupa epops)", value: "Common Hoopoe (Upupa epops)" },
{ label: "Asian Green Bee-eater (Merops orientalis)", value: "Asian Green Bee-eater (Merops orientalis)" },
{ label: "Chestnut-headed Bee-eater (Merops leschenaulti)", value: "Chestnut-headed Bee-eater (Merops leschenaulti)" },
{ label: "Blue-tailed Bee-eater (Merops philippinus)", value: "Blue-tailed Bee-eater (Merops philippinus)" },
{ label: "European Bee-eater (Merops apiaster)", value: "European Bee-eater (Merops apiaster)" },
{ label: "Indian Roller (Coracias benghalensis)", value: "Indian Roller (Coracias benghalensis)" },
{ label: "European Roller (Coracias garrulus)", value: "European Roller (Coracias garrulus)" },
{ label: "Oriental Dollarbird (Eurystomus orientalis)", value: "Oriental Dollarbird (Eurystomus orientalis)" },
{ label: "Oriental Dwarf-kingfisher (Ceyx erithaca)", value: "Oriental Dwarf-kingfisher (Ceyx erithaca)" },
{ label: "Blue-eared Kingfisher (Alcedo meninting)", value: "Blue-eared Kingfisher (Alcedo meninting)" },
{ label: "Common Kingfisher (Alcedo atthis)", value: "Common Kingfisher (Alcedo atthis)" },
{ label: "Pied Kingfisher (Ceryle rudis)", value: "Pied Kingfisher (Ceryle rudis)" },
{ label: "Stork-billed Kingfisher (Pelargopsis capensis)", value: "Stork-billed Kingfisher (Pelargopsis capensis)" },
{ label: "White-breasted Kingfisher (Halcyon smyrnensis)", value: "White-breasted Kingfisher (Halcyon smyrnensis)" },
{ label: "Black-capped Kingfisher (Halcyon pileata)", value: "Black-capped Kingfisher (Halcyon pileata)" },
{ label: "Coppersmith Barbet (Psilopogon haemacephalus)", value: "Coppersmith Barbet (Psilopogon haemacephalus)" },
{ label: "Sri Lanka Barbet (Psilopogon rubricapillus)", value: "Sri Lanka Barbet (Psilopogon rubricapillus)" },
{ label: "Brown-headed Barbet (Psilopogon zeylanicus)", value: "Brown-headed Barbet (Psilopogon zeylanicus)" },
{ label: "Yellow-fronted Barbet (Psilopogon flavifrons)", value: "Yellow-fronted Barbet (Psilopogon flavifrons)" },
{ label: "Eurasian Wryneck (Jynx torquilla)", value: "Eurasian Wryneck (Jynx torquilla)" },
{ label: "Greater Sri Lanka Flameback (Chrysocolaptes stricklandi)", value: "Greater Sri Lanka Flameback (Chrysocolaptes stricklandi)" },
{ label: "Black-rumped Flameback (Dinopium benghalense)", value: "Black-rumped Flameback (Dinopium benghalense)" },
{ label: "White-naped Woodpecker (Chrysocolaptes stricklandi/Crimson-backed Woodpecker)", value: "White-naped Woodpecker (Chrysocolaptes stricklandi/Crimson-backed Woodpecker)" },
{ label: "Lesser Sri Lanka Flameback (Dinopium psarodes)", value: "Lesser Sri Lanka Flameback (Dinopium psarodes)" },
{ label: "Rufous Woodpecker (Micropternus brachyurus)", value: "Rufous Woodpecker (Micropternus brachyurus)" },
{ label: "Streak-throated Woodpecker (Picus xanthopygaeus/Scaly-bellied Woodpecker)", value: "Streak-throated Woodpecker (Picus xanthopygaeus/Scaly-bellied Woodpecker)" },
{ label: "Lesser Yellownape (Picus chlorolophus)", value: "Lesser Yellownape (Picus chlorolophus)" },
{ label: "Yellow-crowned Woodpecker (Leiopicus mahrattensis)", value: "Yellow-crowned Woodpecker (Leiopicus mahrattensis)" },
{ label: "Lesser Kestrel (Falco naumanni)", value: "Lesser Kestrel (Falco naumanni)" },
{ label: "Common Kestrel (Falco tinnunculus)", value: "Common Kestrel (Falco tinnunculus)" },
{ label: "Red-headed Falcon (Falco chicquera)", value: "Red-headed Falcon (Falco chicquera)" },
{ label: "Amur Falcon (Falco amurensis)", value: "Amur Falcon (Falco amurensis)" },
{ label: "Eurasian Hobby (Falco subbuteo)", value: "Eurasian Hobby (Falco subbuteo)" },
{ label: "Oriental Hobby (Falco severus)", value: "Oriental Hobby (Falco severus)" },
{ label: "Peregrine Falcon (Falco peregrinus)", value: "Peregrine Falcon (Falco peregrinus)" },
{ label: "Sri Lanka Hanging-parrot (Loriculus beryllinus)", value: "Sri Lanka Hanging-parrot (Loriculus beryllinus)" },
{ label: "Plum-headed Parakeet (Himalayapsitta cyanocephala)", value: "Plum-headed Parakeet (Himalayapsitta cyanocephala)" },
{ label: "Rose-ringed Parakeet (Alexandrinus krameri)", value: "Rose-ringed Parakeet (Alexandrinus krameri)" },
{ label: "Alexandrine Parakeet (Palaeornis eupatria)", value: "Alexandrine Parakeet (Palaeornis eupatria)" },
{ label: "Emerald-collared Parakeet (Nicopsitta calthrapae)", value: "Emerald-collared Parakeet (Nicopsitta calthrapae)" },
{ label: "Indian Pitta (Pitta brachyura)", value: "Indian Pitta (Pitta brachyura)" },
{ label: "Black-hooded Oriole (Oriolus xanthornus)", value: "Black-hooded Oriole (Oriolus xanthornus)" },
{ label: "Eurasian Golden Oriole (Oriolus oriolus)", value: "Eurasian Golden Oriole (Oriolus oriolus)" },
{ label: "Indian Golden Oriole (Oriolus kundoo)", value: "Indian Golden Oriole (Oriolus kundoo)" },
{ label: "Black-naped Oriole (Oriolus chinensis)", value: "Black-naped Oriole (Oriolus chinensis)" },
{ label: "Small Minivet (Pericrocotus cinnamomeus)", value: "Small Minivet (Pericrocotus cinnamomeus)" },
{ label: "Scarlet Minivet (Pericrocotus flammeus)", value: "Scarlet Minivet (Pericrocotus flammeus)" },
{ label: "Indian Cuckooshrike (Coracina macei)", value: "Indian Cuckooshrike (Coracina macei)" },
{ label: "Black-headed Cuckooshrike (Lalage melanoptera)", value: "Black-headed Cuckooshrike (Lalage melanoptera)" },
{ label: "Ashy Woodswallow (Artamus fuscus)", value: "Ashy Woodswallow (Artamus fuscus)" },
{ label: "Bar-winged Flycatcher-shrike (Hemipus picatus)", value: "Bar-winged Flycatcher-shrike (Hemipus picatus)" },
{ label: "Sri Lanka Woodshrike (Tephrodornis affinis)", value: "Sri Lanka Woodshrike (Tephrodornis affinis)" },
{ label: "Common Iora (Aegithina tiphia)", value: "Common Iora (Aegithina tiphia)" },
{ label: "Marshall’s Iora (Aegithina nigrolutea)", value: "Marshall’s Iora (Aegithina nigrolutea)" },
{ label: "White-browed Fantail (Rhipidura aureola)", value: "White-browed Fantail (Rhipidura aureola)" },
{ label: "Black Drongo (Dicrurus macrocercus)", value: "Black Drongo (Dicrurus macrocercus)" },
{ label: "Ashy Drongo (Dicrurus leucophaeus)", value: "Ashy Drongo (Dicrurus leucophaeus)" },
{ label: "White-bellied Drongo (Dicrurus caerulescens)", value: "White-bellied Drongo (Dicrurus caerulescens)" },
{ label: "Greater Racket-tailed Drongo (Dicrurus paradiseus)", value: "Greater Racket-tailed Drongo (Dicrurus paradiseus)" },
{ label: "Sri Lanka Drongo (Dicrurus lophorinus)", value: "Sri Lanka Drongo (Dicrurus lophorinus)" },
{ label: "Black-naped Monarch (Hypothymis azurea)", value: "Black-naped Monarch (Hypothymis azurea)" },
{ label: "Indian Paradise-flycatcher (Terpsiphone paradisi)", value: "Indian Paradise-flycatcher (Terpsiphone paradisi)" },
{ label: "Brown Shrike (Lanius cristatus)", value: "Brown Shrike (Lanius cristatus)" },
{ label: "Bay-backed Shrike (Lanius vittatus)", value: "Bay-backed Shrike (Lanius vittatus)" },
{ label: "Long-tailed Shrike (Lanius schach)", value: "Long-tailed Shrike (Lanius schach)" },
{ label: "Great Grey Shrike (Lanius excubitor)", value: "Great Grey Shrike (Lanius excubitor)" },
{ label: "Sri Lanka Blue Magpie (Urocissa ornata)", value: "Sri Lanka Blue Magpie (Urocissa ornata)" },
{ label: "House Crow (Corvus splendens)", value: "House Crow (Corvus splendens)" },
{ label: "Large-billed Crow (Corvus macrorhynchos)", value: "Large-billed Crow (Corvus macrorhynchos)" },
{ label: "Grey-headed Canary-flycatcher (Culicicapa ceylonensis)", value: "Grey-headed Canary-flycatcher (Culicicapa ceylonensis)" },
{ label: "Great Tit (Parus major)", value: "Great Tit (Parus major)" },
{ label: "Ashy-crowned Sparrow-lark (Eremopterix griseus)", value: "Ashy-crowned Sparrow-lark (Eremopterix griseus)" },
{ label: "Jerdon’s Bushlark (Mirafra affinis)", value: "Jerdon’s Bushlark (Mirafra affinis)" },
{ label: "Mongolian Short-toed Lark (Calandrella dukhunensis)", value: "Mongolian Short-toed Lark (Calandrella dukhunensis)" },
{ label: "Oriental Skylark (Alauda gulgula)", value: "Oriental Skylark (Alauda gulgula)" },
{ label: "Zitting Cisticola (Cisticola juncidis)", value: "Zitting Cisticola (Cisticola juncidis)" },
{ label: "Grey-breasted Prinia (Prinia hodgsonii)", value: "Grey-breasted Prinia (Prinia hodgsonii)" },
{ label: "Jungle Prinia (Prinia sylvatica)", value: "Jungle Prinia (Prinia sylvatica)" },
{ label: "Ashy Prinia (Prinia socialis)", value: "Ashy Prinia (Prinia socialis)" },
{ label: "Plain Prinia (Prinia inornata)", value: "Plain Prinia (Prinia inornata)" },
{ label: "Common Tailorbird (Orthotomus sutorius)", value: "Common Tailorbird (Orthotomus sutorius)" },
{ label: "Booted Warbler (Iduna caligata)", value: "Booted Warbler (Iduna caligata)" },
{ label: "Sykes’s Warbler (Iduna rama)", value: "Sykes’s Warbler (Iduna rama)" },
{ label: "Black-browed Reed-warbler (Acrocephalus bistrigiceps)", value: "Black-browed Reed-warbler (Acrocephalus bistrigiceps)" },
{ label: "Blyth’s Reed-warbler (Acrocephalus dumetorum)", value: "Blyth’s Reed-warbler (Acrocephalus dumetorum)" },
{ label: "Clamorous Reed-warbler (Acrocephalus stentoreus)", value: "Clamorous Reed-warbler (Acrocephalus stentoreus)" },
{ label: "Pallas’s Grasshopper-warbler (Locustella certhiola)", value: "Pallas’s Grasshopper-warbler (Locustella certhiola)" },
{ label: "Lanceolated Warbler (Locustella lanceolata)", value: "Lanceolated Warbler (Locustella lanceolata)" },
{ label: "Common Grasshopper-warbler (Locustella naevia)", value: "Common Grasshopper-warbler (Locustella naevia)" },
{ label: "Broad-tailed Grassbird (Schoenicola platyurus)", value: "Broad-tailed Grassbird (Schoenicola platyurus)" },
{ label: "Sri Lanka Warbler (Elaphrornis palliseri)", value: "Sri Lanka Warbler (Elaphrornis palliseri)" },
{ label: "Northern House Martin (Delichon urbicum)", value: "Northern House Martin (Delichon urbicum)" },
{ label: "Streak-throated Swallow (Petrochelidon fluvicola)", value: "Streak-throated Swallow (Petrochelidon fluvicola)" },
{ label: "Red-rumped Swallow (Cecropis daurica)", value: "Red-rumped Swallow (Cecropis daurica)" },
{ label: "Sri Lanka Swallow (Cecropis hyperythra)", value: "Sri Lanka Swallow (Cecropis hyperythra)" },
{ label: "House Swallow (Delichon nipalense)", value: "House Swallow (Delichon nipalense)" },
{ label: "Wire-tailed Swallow (Hirundo smithii)", value: "Wire-tailed Swallow (Hirundo smithii)" },
{ label: "Barn Swallow (Hirundo rustica)", value: "Barn Swallow (Hirundo rustica)" },
{ label: "Dusky Crag Martin (Ptyonoprogne concolor)", value: "Dusky Crag Martin (Ptyonoprogne concolor)" },
{ label: "Collared Sand Martin (Riparia riparia)", value: "Collared Sand Martin (Riparia riparia)" },
{ label: "Square-tailed Bulbul (Hypsipetes ganeesa)", value: "Square-tailed Bulbul (Hypsipetes ganeesa)" },
{ label: "Black-capped Bulbul (Rubigula melanicterus)", value: "Black-capped Bulbul (Rubigula melanicterus)" },
{ label: "Red-vented Bulbul (Pycnonotus cafer)", value: "Red-vented Bulbul (Pycnonotus cafer)" },
{ label: "Yellow-eared Bulbul (Pycnonotus penicillatus)", value: "Yellow-eared Bulbul (Pycnonotus penicillatus)" },
{ label: "White-browed Bulbul (Pycnonotus luteolus)", value: "White-browed Bulbul (Pycnonotus luteolus)" },
{ label: "Yellow-browed Bulbul (Acritillas indica)", value: "Yellow-browed Bulbul (Acritillas indica)" },
{ label: "Dusky Warbler (Phylloscopus fuscatus)", value: "Dusky Warbler (Phylloscopus fuscatus)" },
{ label: "Green Warbler (Phylloscopus nitidus)", value: "Green Warbler (Phylloscopus nitidus)" },
{ label: "Greenish Warbler (Phylloscopus trochiloides)", value: "Greenish Warbler (Phylloscopus trochiloides)" },
{ label: "Large-billed Leaf-warbler (Phylloscopus magnirostris)", value: "Large-billed Leaf-warbler (Phylloscopus magnirostris)" },
{ label: "Western Crowned Leaf-warbler (Phylloscopus occipitalis)", value: "Western Crowned Leaf-warbler (Phylloscopus occipitalis)" },
{ label: "Lesser Whitethroat (Curruca curruca)", value: "Lesser Whitethroat (Curruca curruca)" },
{ label: "Yellow-eyed Babbler (Chrysomma sinense)", value: "Yellow-eyed Babbler (Chrysomma sinense)" },
{ label: "Sri Lanka White-eye (Zosterops ceylonensis)", value: "Sri Lanka White-eye (Zosterops ceylonensis)" },
{ label: "Indian White-eye (Zosterops palpebrosus)", value: "Indian White-eye (Zosterops palpebrosus)" },
{ label: "Sri Lanka Scimitar-babbler (Pomatorhinus melanurus)", value: "Sri Lanka Scimitar-babbler (Pomatorhinus melanurus)" },
{ label: "Tawny-bellied Babbler (Dumetia hyperythra)", value: "Tawny-bellied Babbler (Dumetia hyperythra)" },
{ label: "Dark-fronted Babbler (Rhopocichla atriceps)", value: "Dark-fronted Babbler (Rhopocichla atriceps)" },
{ label: "Brown-capped Babbler (Pellorneum fuscocapillus)", value: "Brown-capped Babbler (Pellorneum fuscocapillus)" },
{ label: "Ashy-headed Laughingthrush (Garrulax cinereifrons)", value: "Ashy-headed Laughingthrush (Garrulax cinereifrons)" },
{ label: "Orange-billed Babbler (Argya rufescens)", value: "Orange-billed Babbler (Argya rufescens)" },
{ label: "Yellow-billed Babbler (Argya affinis)", value: "Yellow-billed Babbler (Argya affinis)" },
{ label: "Velvet-fronted Nuthatch (Sitta frontalis)", value: "Velvet-fronted Nuthatch (Sitta frontalis)" },
{ label: "Rosy Starling (Pastor roseus)", value: "Rosy Starling (Pastor roseus)" },
{ label: "Purple-backed Starling (Agropsar sturninus)", value: "Purple-backed Starling (Agropsar sturninus)" },
{ label: "White-faced Starling (Sturnornis albofrontatus)", value: "White-faced Starling (Sturnornis albofrontatus)" },
{ label: "Brahminy Starling (Sturnia pagodarum)", value: "Brahminy Starling (Sturnia pagodarum)" },
{ label: "Chestnut-tailed Starling (Sturnia malabarica)", value: "Chestnut-tailed Starling (Sturnia malabarica)" },
{ label: "Common Myna (Acridotheres tristis)", value: "Common Myna (Acridotheres tristis)" },
{ label: "Southern Hill Myna (Gracula indica) ", value: "Southern Hill Myna (Gracula indica) " },
{ label: "Sri Lanka Hill Myna (Gracula ptilogenys)", value: "Sri Lanka Hill Myna (Gracula ptilogenys)" },
{ label: "White's Thrush (Zoothera aurea)", value: "White's Thrush (Zoothera aurea)" },
{ label: "Pied Thrush (Geokichla wardii)", value: "Pied Thrush (Geokichla wardii)" },
{ label: "Spot-winged Thrush (Geokichla spiloptera)", value: "Spot-winged Thrush (Geokichla spiloptera)" },
{ label: "Orange-headed Thrush (Geokichla citrina)", value: "Orange-headed Thrush (Geokichla citrina)" },
{ label: "Indian Blackbird (Turdus simillimus)", value: "Indian Blackbird (Turdus simillimus)" },
{ label: "Eyebrowed Thrush (Turdus obscurus)", value: "Eyebrowed Thrush (Turdus obscurus)" },
{ label: "Rufous-tailed Scrub-robin (Cercotrichas galactotes)", value: "Rufous-tailed Scrub-robin (Cercotrichas galactotes)" },
{ label: "Oriental Magpie-robin (Copsychus saularis)", value: "Oriental Magpie-robin (Copsychus saularis)" },
{ label: "Indian Robin (Copsychus fulicatus)", value: "Indian Robin (Copsychus fulicatus)" },
{ label: "White-rumped Shama (Copsychus malabaricus)", value: "White-rumped Shama (Copsychus malabaricus)" },
{ label: "Brown-breasted Flycatcher (Muscicapa muttui)", value: "Brown-breasted Flycatcher (Muscicapa muttui)" },
{ label: "Asian Brown Flycatcher (Muscicapa dauurica)", value: "Asian Brown Flycatcher (Muscicapa dauurica)" },
{ label: "Blue-and-White Flycatcher (Cyanoptila cyanomelana)", value: "Blue-and-White Flycatcher (Cyanoptila cyanomelana)" },
{ label: "Dull-blue Flycatcher (Eumyias sordidus)", value: "Dull-blue Flycatcher (Eumyias sordidus)" },
{ label: "Tickell’s Blue-flycatcher (Cyornis tickelliae)", value: "Tickell’s Blue-flycatcher (Cyornis tickelliae)" },
{ label: "Blue-throated Blue-flycatcher (Cyornis rubeculoides)", value: "Blue-throated Blue-flycatcher (Cyornis rubeculoides)" },
{ label: "Indian Blue Robin (Larvivora brunnea)", value: "Indian Blue Robin (Larvivora brunnea)" },
{ label: "Bluethroat (Luscinia svecica)", value: "Bluethroat (Luscinia svecica)" },
{ label: "Sri Lanka Whistling-thrush (Myophonus blighi)", value: "Sri Lanka Whistling-thrush (Myophonus blighi)" },
{ label: "Yellow-rumped Flycatcher (Ficedula zanthopygia)", value: "Yellow-rumped Flycatcher (Ficedula zanthopygia)" },
{ label: "Kashmir Flycatcher (Ficedula subrubra)", value: "Kashmir Flycatcher (Ficedula subrubra)" },
{ label: "Rufous-tailed Rock-thrush (Monticola saxatilis)", value: "Rufous-tailed Rock-thrush (Monticola saxatilis)" },
{ label: "Blue Rock-thrush (Monticola solitarius)", value: "Blue Rock-thrush (Monticola solitarius)" },
{ label: "Whinchat (Saxicola rubetra)", value: "Whinchat (Saxicola rubetra)" },
{ label: "Pied Bushchat (Saxicola caprata)", value: "Pied Bushchat (Saxicola caprata)" },
{ label: "Common Stonechat (Saxicola torquatus)", value: "Common Stonechat (Saxicola torquatus)" },
{ label: "Northern Wheatear (Oenanthe oenanthe)", value: "Northern Wheatear (Oenanthe oenanthe)" },
{ label: "Isabelline Wheatear (Oenanthe isabellina)", value: "Isabelline Wheatear (Oenanthe isabellina)" },
{ label: "Desert Wheatear (Oenanthe deserti)", value: "Desert Wheatear (Oenanthe deserti)" },
{ label: "Pied Wheatear (Oenanthe pleschanka)", value: "Pied Wheatear (Oenanthe pleschanka)" },
{ label: "Asian Fairy-bluebird (Irena puella)", value: "Asian Fairy-bluebird (Irena puella)" },
{ label: "Golden-fronted Leafbird (Chloropsis aurifrons)", value: "Golden-fronted Leafbird (Chloropsis aurifrons)" },
{ label: "Jerdon's Leafbird (Chloropsis jerdoni)", value: "Jerdon's Leafbird (Chloropsis jerdoni)" },
{ label: "White-throated Flowerpecker (Dicaeum vincens)", value: "White-throated Flowerpecker (Dicaeum vincens)" },
{ label: "Thick-billed Flowerpecker (Dicaeum agile)", value: "Thick-billed Flowerpecker (Dicaeum agile)" },
{ label: "Pale-billed Flowerpecker (Dicaeum erythrorhynchos)", value: "Pale-billed Flowerpecker (Dicaeum erythrorhynchos)" },
{ label: "Purple-rumped Sunbird (Leptocoma zeylonica)", value: "Purple-rumped Sunbird (Leptocoma zeylonica)" },
{ label: "Purple Sunbird (Cinnyris asiaticus)", value: "Purple Sunbird (Cinnyris asiaticus)" },
{ label: "Loten’s Sunbird (Cinnyris lotenius)", value: "Loten’s Sunbird (Cinnyris lotenius)" },
{ label: "Streaked Weaver (Ploceus manyar)", value: "Streaked Weaver (Ploceus manyar)" },
{ label: "Baya Weaver (Ploceus philippinus)", value: "Baya Weaver (Ploceus philippinus)" },
{ label: "Indian Silverbill (Euodice malabarica)", value: "Indian Silverbill (Euodice malabarica)" },
{ label: "White-rumped Munia (Lonchura striata)", value: "White-rumped Munia (Lonchura striata)" },
{ label: "Scaly-breasted Munia (Lonchura punctulata)", value: "Scaly-breasted Munia (Lonchura punctulata)" },
{ label: "Black-throated Munia (Lonchura kelaarti)", value: "Black-throated Munia (Lonchura kelaarti)" },
{ label: "Tricoloured Munia (Lonchura malacca)", value: "Tricoloured Munia (Lonchura malacca)" },
{ label: "House Sparrow (Passer domesticus)", value: "House Sparrow (Passer domesticus)" },
{ label: "Chestnut-shouldered Bush-sparrow (Gymnoris xanthocollis)", value: "Chestnut-shouldered Bush-sparrow (Gymnoris xanthocollis)" },
{ label: "Forest Wagtail (Dendronanthus indicus)", value: "Forest Wagtail (Dendronanthus indicus)" },
{ label: "Olive-backed Pipit (Anthus hodgsoni)", value: "Olive-backed Pipit (Anthus hodgsoni)" },
{ label: "Red-throated Pipit (Anthus cervinus)", value: "Red-throated Pipit (Anthus cervinus)" },
{ label: "Richard's Pipit (Anthus richardi)", value: "Richard's Pipit (Anthus richardi)" },
{ label: "Paddyfield Pipit (Anthus rufulus)", value: "Paddyfield Pipit (Anthus rufulus)" },
{ label: "Blyth's Pipit (Anthus godlewskii)", value: "Blyth's Pipit (Anthus godlewskii)" },
{ label: "Tawny Pipit (Anthus campestris)", value: "Tawny Pipit (Anthus campestris)" },
{ label: "Western Yellow Wagtail (Motacilla flava)", value: "Western Yellow Wagtail (Motacilla flava)" },
{ label: "Grey Wagtail (Motacilla cinerea)", value: "Grey Wagtail (Motacilla cinerea)" },
{ label: "Citrine Wagtail (Motacilla citreola)", value: "Citrine Wagtail (Motacilla citreola)" },
{ label: "White-browed Wagtail (Motacilla maderaspatensis)", value: "White-browed Wagtail (Motacilla maderaspatensis)" },
{ label: "White Wagtail (Motacilla alba)", value: "White Wagtail (Motacilla alba)" },
{ label: "Common Rosefinch (Carpodacus erythrinus)", value: "Common Rosefinch (Carpodacus erythrinus)" },
{ label: "Black-headed Bunting (Emberiza melanocephala)", value: "Black-headed Bunting (Emberiza melanocephala)" },
{ label: "Red-headed Bunting (Emberiza bruniceps)", value: "Red-headed Bunting (Emberiza bruniceps)" },
{ label: "Grey-necked Bunting (Emberiza buchanani)", value: "Grey-necked Bunting (Emberiza buchanani)" },
{ label: "Wood Snipe (Gallinago nemoricola)", value: "Wood Snipe (Gallinago nemoricola)" },
  { label: "Pintail Snipe (Gallinago stenura)", value: "Pintail Snipe (Gallinago stenura)" },
  { label: "Swinhoe's Snipe (Gallinago megala)", value: "Swinhoe's Snipe (Gallinago megala)" },
  { label: "Great Snipe (Gallinago media)", value: "Great Snipe (Gallinago media)" },
  { label: "Common Snipe (Gallinago gallinago)", value: "Common Snipe (Gallinago gallinago)" },
  { label: "Jack Snipe (Lymnocryptes minimus)", value: "Jack Snipe (Lymnocryptes minimus)" },
  { label: "Red-necked Phalarope (Phalaropus lobatus)", value: "Red-necked Phalarope (Phalaropus lobatus)" },
  { label: "Terek Sandpiper (Xenus cinereus)", value: "Terek Sandpiper (Xenus cinereus)" },
  { label: "Common Sandpiper (Actitis hypoleucos)", value: "Common Sandpiper (Actitis hypoleucos)" },
  { label: "Green Sandpiper (Tringa ochropus)", value: "Green Sandpiper (Tringa ochropus)" },
  { label: "Spotted Redshank (Tringa erythropus)", value: "Spotted Redshank (Tringa erythropus)" },
  { label: "Common Greenshank (Tringa nebularia)", value: "Common Greenshank (Tringa nebularia)" },
  { label: "Common Redshank (Tringa totanus)", value: "Common Redshank (Tringa totanus)" },
  { label: "Wood Sandpiper (Tringa glareola)", value: "Wood Sandpiper (Tringa glareola)" },
  { label: "Marsh Sandpiper (Tringa stagnatilis)", value: "Marsh Sandpiper (Tringa stagnatilis)" },
  { label: "Common Buttonquail (Turnix sylvaticus)", value: "Common Buttonquail (Turnix sylvaticus)" },
  { label: "Barred Buttonquail (Turnix suscitator)", value: "Barred Buttonquail (Turnix suscitator)" },
  { label: "Crab-plover (Dromas ardeola)", value: "Crab-plover (Dromas ardeola)" },
  { label: "Indian Courser (Cursorius coromandelicus)", value: "Indian Courser (Cursorius coromandelicus)" },
  { label: "Collared Pratincole (Glareola pratincola)", value: "Collared Pratincole (Glareola pratincola)" },
  { label: "Oriental Pratincole (Glareola maldivarum)", value: "Oriental Pratincole (Glareola maldivarum)" },
  { label: "Little Pratincole (Glareola lactea)", value: "Little Pratincole (Glareola lactea)" },
  { label: "Brown Noddy (Anous stolidus)", value: "Brown Noddy (Anous stolidus)" },
  { label: "Lesser Noddy (Anous tenuirostris)", value: "Lesser Noddy (Anous tenuirostris)" },
  { label: "Slender-billed Gull (Larus genei)", value: "Slender-billed Gull (Larus genei)" },
  { label: "Brown-headed Gull (Larus brunnicephalus)", value: "Brown-headed Gull (Larus brunnicephalus)" },
  { label: "Black-headed Gull (Larus ridibundus)", value: "Black-headed Gull (Larus ridibundus)" },
  { label: "Pallas’s Gull (Larus ichthyaetus)", value: "Pallas’s Gull (Larus ichthyaetus)" },
  { label: "Sooty Gull (Larus hemprichii)", value: "Sooty Gull (Larus hemprichii)" },
  { label: "Lesser Black-backed Gull (Larus fuscus)", value: "Lesser Black-backed Gull (Larus fuscus)" },
  { label: "Sooty Tern (Onychoprion fuscatus)", value: "Sooty Tern (Onychoprion fuscatus)" },
  { label: "Bridled Tern (Onychoprion anaethetus)", value: "Bridled Tern (Onychoprion anaethetus)" },
  { label: "Little Tern (Sternula albifrons)", value: "Little Tern (Sternula albifrons)" },
  { label: "Saunders's Tern (Sternula saundersi)", value: "Saunders's Tern (Sternula saundersi)" },
  { label: "Common Gull-billed Tern (Gelochelidon nilotica)", value: "Common Gull-billed Tern (Gelochelidon nilotica)" },
  { label: "Caspian Tern (Hydroprogne caspia)", value: "Caspian Tern (Hydroprogne caspia)" },
  { label: "Whiskered Tern (Chlidonias hybrida)", value: "Whiskered Tern (Chlidonias hybrida)" },
  { label: "White-winged Tern (Chlidonias leucopterus)", value: "White-winged Tern (Chlidonias leucopterus)" },
  { label: "Black Tern (Chlidonias niger)", value: "Black Tern (Chlidonias niger)" },
  { label: "Roseate Tern (Sterna dougallii)", value: "Roseate Tern (Sterna dougallii)" },
  { label: "Indian Pygmy Woodpecker (Picoides nanus)", value: "Indian Pygmy Woodpecker (Picoides nanus)" },
  { label: "Yellow-crowned Woodpecker (Leiopicus mahrattensis)", value: "Yellow-crowned Woodpecker (Leiopicus mahrattensis)" },
  { label: "Black-naped Tern (Sterna sumatrana)", value: "Black-naped Tern (Sterna sumatrana)" },
  { label: "Common Tern (Sterna hirundo)", value: "Common Tern (Sterna hirundo)" },
  { label: "Lesser Crested Tern (Thalasseus bengalensis)", value: "Lesser Crested Tern (Thalasseus bengalensis)" },
  { label: "Sandwich Tern (Thalasseus sandvicensis)", value: "Sandwich Tern (Thalasseus sandvicensis)" },
  { label: "Greater Crested Tern (Thalasseus bergii)", value: "Greater Crested Tern (Thalasseus bergii)" },
  { label: "Long-tailed Jaeger (Stercorarius longicaudus)", value: "Long-tailed Jaeger (Stercorarius longicaudus)" },
  { label: "Arctic Jaeger (Stercorarius parasiticus)", value: "Arctic Jaeger (Stercorarius parasiticus)" },
  { label: "Pomarine Jaeger (Stercorarius pomarinus)", value: "Pomarine Jaeger (Stercorarius pomarinus)" },
  { label: "South Polar Skua (Catharacta maccormicki)", value: "South Polar Skua (Catharacta maccormicki)" },
  { label: "Brown Skua (Catharacta antarctica)", value: "Brown Skua (Catharacta antarctica)" }


    ];
    
    export default birdSpecies;